# Generated by Django 2.0.1 on 2018-05-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='payconn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.PaymentMethod'),
        ),
    ]
