# Generated by Django 2.0.1 on 2018-05-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_payconn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='payconn',
            new_name='pmethod',
        ),
    ]
