# Generated by Django 2.0.1 on 2018-05-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
