# Generated by Django 2.0.1 on 2018-05-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barzel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icc', models.CharField(max_length=30, null=True)),
                ('barzel', models.ManyToManyField(null=True, related_name='sbcon', to='cellular.Barzel')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sccon', to='cellular.Card')),
            ],
        ),
    ]
