# Generated by Django 2.0.1 on 2018-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='barzel',
            field=models.ManyToManyField(related_name='sbcon', to='cellular.Barzel'),
        ),
    ]
