# Generated by Django 2.0.1 on 2018-05-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellular', '0002_auto_20180530_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarzelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sim',
            name='icc',
            field=models.CharField(max_length=30, null=True, verbose_name='ICC'),
        ),
        migrations.AddField(
            model_name='barzel',
            name='btype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cellular.BarzelType'),
        ),
    ]
